/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import ModeloConection.ConexaoBd;
import ModeloDao.DaoAlias;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Lucas
 */
public class FormAliasAlterado extends javax.swing.JFrame {

    private static File arquivo;
    String Url;
    DaoAlias alias = new DaoAlias();
    //ModeloAlias alias;

    /**
     * Creates new form FormBancoDados
     */
    public FormAliasAlterado() {
        initComponents();
        percorrerAlias();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelServidor = new javax.swing.JLabel();
        jLabelBd = new javax.swing.JLabel();
        jLabelAlias = new javax.swing.JLabel();
        jTextFieldAlias = new javax.swing.JTextField();
        jTextFieldServidor = new javax.swing.JTextField();
        jTextFieldDataBaseName = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jlistAlias = new java.awt.List();
        jButtonTestarConexao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabelPorta = new javax.swing.JLabel();
        jTextFieldPorta = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jRadioButtonAtivarProfiler = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Alias");
        setResizable(false);

        jLabelServidor.setText("Servidor: ");

        jLabelBd.setText("Banco de Dados: ");

        jLabelAlias.setText("Alias: ");

        jTextFieldAlias.setEnabled(false);

        jTextFieldServidor.setEnabled(false);

        jTextFieldDataBaseName.setEnabled(false);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jlistAlias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlistAlias.setName(""); // NOI18N
        jlistAlias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlistAliasMouseClicked(evt);
            }
        });
        jlistAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistAliasActionPerformed(evt);
            }
        });

        jButtonTestarConexao.setText("Testar Conexão");
        jButtonTestarConexao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTestarConexaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTestarConexaoMouseEntered(evt);
            }
        });
        jButtonTestarConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestarConexaoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Gerenciamento de alias");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelPorta.setText("Porta:");

        jTextFieldPorta.setEnabled(false);

        jButtonIncluir.setText("Novo");
        jButtonIncluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIncluirMouseClicked(evt);
            }
        });
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setDoubleBuffered(true);
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jRadioButtonAtivarProfiler.setText("Ativar profiler banco de dados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonIncluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAtivarProfiler)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlistAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelAlias)
                                    .addComponent(jLabelServidor)
                                    .addComponent(jLabelBd)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPorta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldServidor)
                                    .addComponent(jTextFieldAlias)
                                    .addComponent(jTextFieldDataBaseName)
                                    .addComponent(jButtonTestarConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAlias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelServidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPorta)
                            .addComponent(jTextFieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTestarConexao))
                    .addComponent(jlistAlias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSair)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAtivarProfiler)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(451, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTestarConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestarConexaoActionPerformed
        if (jTextFieldDataBaseName.getText().isEmpty() & jTextFieldPorta.getText().isEmpty()
                & jTextFieldServidor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe os dados do servidor do banco!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonTestarConexaoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:

        alias.CriaAlias();

        alias.salvar(jTextFieldAlias.getText(), jTextFieldServidor.getText(), jTextFieldDataBaseName.getText(),
                jTextFieldPorta.getText());
        jlistAlias.removeAll();
        percorrerAlias();
        limparCampos();

        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonIncluir.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);

        jTextFieldAlias.enable(false);
        jTextFieldDataBaseName.enable(false);
        jTextFieldPorta.enable(false);
        jTextFieldServidor.enable(false);

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonIncluir.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);

        jTextFieldAlias.enable(true);
        jTextFieldDataBaseName.enable(true);
        jTextFieldPorta.enable(true);
        jTextFieldServidor.enable(true);
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonIncluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIncluirMouseClicked
        limparCampos();
    }//GEN-LAST:event_jButtonIncluirMouseClicked

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonSalvarMouseClicked

    private void jButtonTestarConexaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTestarConexaoMouseClicked

        Url = "jdbc:sqlserver://" + jTextFieldServidor.getText() + ":" + jTextFieldPorta.getText() + ";databaseName="
                + jTextFieldDataBaseName.getText();
        ConexaoBd conexaoBD = new ConexaoBd();
     //   conexaoBD.conectarBd(Url, 1);
        conexaoBD.DesconectarBd();
    }//GEN-LAST:event_jButtonTestarConexaoMouseClicked

    private void jButtonTestarConexaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTestarConexaoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTestarConexaoMouseEntered

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldAlias.enable(false);
        jTextFieldDataBaseName.enable(false);
        jTextFieldPorta.enable(false);
        jTextFieldServidor.enable(false);

        jButtonCancelar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonIncluir.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
//        ModeloAlias alias = new ModeloAlias();
//        alias.percorrerAlias();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jlistAliasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlistAliasMouseClicked

        BufferedReader arquivo = null;
        limparCampos();

        try {
            DaoAlias txt = new DaoAlias();
            String Nome = String.valueOf(jlistAlias.getSelectedItem());
        
            arquivo = new BufferedReader(new FileReader(txt.file));

            try {
                while (arquivo.ready()) {
                    String linha = arquivo.readLine();
                    String[] valoresEntreVirgulas = linha.split(";");
                   
                    if (Nome.contains(valoresEntreVirgulas[0])) {

                        jTextFieldAlias.setText(valoresEntreVirgulas[0]);
                        jTextFieldServidor.setText(valoresEntreVirgulas[1]);
                        jTextFieldDataBaseName.setText(valoresEntreVirgulas[2]);
                        jTextFieldPorta.setText(valoresEntreVirgulas[3]);
                    }
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro na leitura do arquivo: \n" + ex.getMessage());
            }
        } catch (FileNotFoundException ex) {
             JOptionPane.showMessageDialog(null, "Arquivo não foi loocalizado. \n" + ex.getMessage());
        } finally {
            try {
                arquivo.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao fechar o arquivo Alias. \n" + ex.getMessage());
            }
        }
        jButtonIncluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(true);
    }//GEN-LAST:event_jlistAliasMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonIncluir.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jlistAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistAliasActionPerformed
        jButtonEditar.setEnabled(true);
    }//GEN-LAST:event_jlistAliasActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

        jTextFieldAlias.setEnabled(true);
        jTextFieldDataBaseName.setEnabled(true);
        jTextFieldPorta.setEnabled(true);
        jTextFieldServidor.setEnabled(true);

        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonIncluir.setEnabled(false);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonEditarActionPerformed
    public void limparCampos() {
        jTextFieldAlias.setText(" ");
        jTextFieldDataBaseName.setText(" ");
        jTextFieldServidor.setText(" ");
        jTextFieldPorta.setText(" ");
    }

    public void percorrerAlias() {
        DaoAlias txt = new DaoAlias();
        try {
            //cria um scanner para ler o arquivo
            Scanner leitor = new Scanner(txt.file);
            //variavel que armazenara as linhas do arquivo
            String linhasDoArquivo = new String();
            //percorre todo o arquivo
            while (leitor.hasNext()) {
                //recebe cada linha do arquivo
                linhasDoArquivo = leitor.nextLine();
                //separa os campos entre as virgulas de cada linha
                String[] valoresEntreVirgulas = linhasDoArquivo.split(";");
                //imprime a coluna que quiser
                jlistAlias.add(valoresEntreVirgulas[0]);
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showConfirmDialog(rootPane, "Erro ao carregar os dados: " + e);
        }
    }
//https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FilenameUtils.html#method_detail
    //http://www.guj.com.br/t/como-ler-apenas-a-linha-20-de-um-txt/136542/5

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAliasAlterado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAliasAlterado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAliasAlterado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAliasAlterado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAliasAlterado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonTestarConexao;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAlias;
    private javax.swing.JLabel jLabelBd;
    private javax.swing.JLabel jLabelPorta;
    private javax.swing.JLabel jLabelServidor;
    private javax.swing.JRadioButton jRadioButtonAtivarProfiler;
    private javax.swing.JTextField jTextFieldAlias;
    private javax.swing.JTextField jTextFieldDataBaseName;
    private javax.swing.JTextField jTextFieldPorta;
    private javax.swing.JTextField jTextFieldServidor;
    private java.awt.List jlistAlias;
    // End of variables declaration//GEN-END:variables
}
/**
 * BufferedReader arquivo = new BufferedReader(new
 * FileReader("caminho_do_arquivo")); while(arquivo.ready()) { * // pega a linha
 * String linha = arquivo.readLine();
 * System.out.println(linha.substring(linha.indexOf("<xMotivo>") +
 * "<xMotivo>".length(), linha.indexOf("</xMotivo>"))); * }
 * http://www.javac.com.br/jc/posts/list/215-pegar-informacao-de-um-arquivo-txt-resolvido.page
 *
 */
