/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import ModeloBeans.BeansDadosUsuario;
import ModeloBeans.BeansPaciente;
import ModeloBeans.ModeloTabela;
import ModeloConection.ConexaoBd;
import ModeloConection.WebServiceCep;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import ModeloDao.DaoPaciente;

/**
 *
 * @author Daniel Lucas
 */
public class FormPaciente extends javax.swing.JFrame {

    ConexaoBd conBd = new ConexaoBd();
    BeansPaciente pac = new BeansPaciente();
    DaoPaciente controlP = new DaoPaciente();

    ResultSet rs = null;
    PreparedStatement pstP;

    int flag = 0;

    /**
     * Creates new form FormPaciente
     */
    public FormPaciente() {
        // initComponents();
    }

    public FormPaciente(BeansDadosUsuario beansDadosUsuario) {
        initComponents();
        preencherTabelaPaciente("SELECT IDPACIENTE,NOMEPACIENTE,TELRESIDENCIAL,TELCELULAR,EMAIL FROM PACIENTE (NOLOCK) ORDER BY NOMEPACIENTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modeloify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldPEmerTelRes1 = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPEmerTelCel = new javax.swing.JFormattedTextField();
        jTextFieldPEmerNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPIdPaciente = new javax.swing.JTextField();
        jTextFieldPNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jButtonPPesquisar = new javax.swing.JButton();
        jTextFieldPPesquisar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPendereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPBairro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPNumero = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPUf = new javax.swing.JTextField();
        jTextFieldPCidade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldPCep = new javax.swing.JFormattedTextField();
        jButtonBuscarCep = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldPComplemento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldPRg = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldPCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPDtNascimento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldPTelRes = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldPTelCel = new javax.swing.JFormattedTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Formulário Paciente");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel2.setText("Nome: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato Emergencial"));

        jLabel8.setText("Nome:");

        jLabel9.setText("Telefone Celular");

        jLabel10.setText("Telefone Residencial");

        try {
            jFormattedTextFieldPEmerTelRes1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPEmerTelRes1.setEnabled(false);

        try {
            jFormattedTextFieldPEmerTelCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPEmerTelCel.setEnabled(false);

        jTextFieldPEmerNome.setEnabled(false);
        jTextFieldPEmerNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPEmerNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPEmerNome))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldPEmerTelRes1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldPEmerTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPEmerNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jFormattedTextFieldPEmerTelRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jFormattedTextFieldPEmerTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel11.setText("ID Paciente:");

        jTextFieldPIdPaciente.setEnabled(false);
        jTextFieldPIdPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPIdPacienteActionPerformed(evt);
            }
        });

        jTextFieldPNome.setEnabled(false);

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePaciente);

        jButtonPPesquisar.setText("Pesquisar");
        jButtonPPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPPesquisarMouseClicked(evt);
            }
        });
        jButtonPPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPPesquisarActionPerformed(evt);
            }
        });

        jLabel12.setText("Endereço :");

        jTextFieldPendereco.setEnabled(false);

        jLabel13.setText("Bairro:");

        jTextFieldPBairro.setEnabled(false);

        jLabel14.setText("Número :");

        jTextFieldPNumero.setEnabled(false);

        jLabel15.setText("UF :");

        jLabel16.setText("Cidade :");

        jTextFieldPUf.setEnabled(false);

        jTextFieldPCidade.setEnabled(false);

        jLabel17.setText("CEP :");

        try {
            jFormattedTextFieldPCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPCep.setEnabled(false);

        jButtonBuscarCep.setText("Buscar");
        jButtonBuscarCep.setEnabled(false);
        jButtonBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCepActionPerformed(evt);
            }
        });

        jLabel18.setText("E-mail :");

        jTextFieldPEmail.setEnabled(false);

        jLabel19.setText("Complemento :");

        jTextFieldPComplemento.setEnabled(false);

        jLabel4.setText("RG :");

        try {
            jFormattedTextFieldPRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPRg.setEnabled(false);
        jFormattedTextFieldPRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPRgActionPerformed(evt);
            }
        });

        jLabel5.setText("CPF :");

        try {
            jFormattedTextFieldPCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPCpf.setEnabled(false);
        jFormattedTextFieldPCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPCpfActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldPDtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPDtNascimento.setEnabled(false);

        jLabel3.setText("Data Nascimento:");

        jLabel6.setText("Telefone Residencial :");

        try {
            jFormattedTextFieldPTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPTelRes.setEnabled(false);
        jFormattedTextFieldPTelRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPTelResActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefone Celular :");

        try {
            jFormattedTextFieldPTelCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPTelCel.setEnabled(false);

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldPNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldPRg, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFormattedTextFieldPCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jTextFieldPCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPUf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextFieldPendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jTextFieldPNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jFormattedTextFieldPTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jFormattedTextFieldPTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jFormattedTextFieldPDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel17)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jFormattedTextFieldPCep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonBuscarCep, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel19)
                                .addComponent(jLabel18)
                                .addComponent(jTextFieldPEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                .addComponent(jTextFieldPComplemento)))
                        .addGap(18, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPPesquisar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldPNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldPRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldPCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextFieldPTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldPTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldPDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jTextFieldPCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel16)))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldPCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarCep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(498, 498, 498)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        //Limpar os campos
        LimparCampos();
        //Habilitar ou Desabilitar Campos
        DesabilitarCampos();
        jButtonBuscarCep.setEnabled(!true);
        jTextFieldPPesquisar.setEnabled(true);

        jButtonCancelar.setEnabled(!true);
        jButtonSalvar.setEnabled(false);
        jButtonIncluir.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabelaPaciente("SELECT IDPACIENTE,NOMEPACIENTE,TELRESIDENCIAL,EMAIL,TELCELULAR FROM PACIENTE (NOLOCK) ORDER BY NOMEPACIENTE");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;

        try {
            pac.setPCod(Integer.parseInt(jTextFieldPIdPaciente.getText()));
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir? ");

            if (resposta == JOptionPane.YES_OPTION) {

                controlP.Excluir(pac);
                preencherTabelaPaciente("SELECT IDPACIENTE,NOMEPACIENTE,TELRESIDENCIAL,TELCELULAR,EMAIL FROM PACIENTE(NOLOCK) ORDER BY NOMEPACIENTE ");

                jButtonSalvar.setEnabled(false);
                jButtonBuscarCep.setEnabled(!true);
                jButtonCancelar.setEnabled(!false);
                jButtonIncluir.setEnabled(true);
                jButtonExcluir.setEnabled(false);
                jButtonEditar.setEnabled(false);

                LimparCampos();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um regisro a ser excluido.");
        }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:

        if (jTextFieldPNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o NOME para continuar.");
            jTextFieldPNome.requestFocus();
        } else if (jFormattedTextFieldPTelCel.getText().equals("(   )     -    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o Telefone celular do paciente para continuar.");
            jFormattedTextFieldPTelCel.requestFocus();
        }

        if (flag == 1) {
            //Ler campos da tela de cadastro do medico

            pac.setPNome(jTextFieldPNome.getText());
            pac.setPRg(jFormattedTextFieldPRg.getText());
            pac.setPCpf(jFormattedTextFieldPCpf.getText());
            pac.setPBairro(jTextFieldPBairro.getText());
            pac.setPUf(jTextFieldPUf.getText());
            pac.setPCidade(jTextFieldPCidade.getText());
            pac.setPLogradouro(jTextFieldPendereco.getText());
            pac.setPNumero(Integer.parseInt(jTextFieldPNumero.getText()));
            pac.setPCompl(jTextFieldPComplemento.getText());
            pac.setPCep(jFormattedTextFieldPCep.getText());
            pac.setPDtNascimento(jFormattedTextFieldPDtNascimento.getText());
            pac.setPTelCelular(jFormattedTextFieldPTelCel.getText());
            pac.setPTelResidencial(jFormattedTextFieldPTelRes.getText());
            pac.setPEmail(jTextFieldPEmail.getText());
            pac.setPEmerNome(jTextFieldPEmerNome.getText());
            pac.setPEmerTelCelular(jFormattedTextFieldPEmerTelCel.getText());
            pac.setPEmerTelResidencial(jFormattedTextFieldPEmerTelRes1.getText());

            controlP.salvar(pac);

            //Limpar os campos
            LimparCampos();

        } else if (flag == 2) {

            pac.setPNome(jTextFieldPNome.getText());
            pac.setPRg(jFormattedTextFieldPRg.getText());
            pac.setPCpf(jFormattedTextFieldPCpf.getText());
            pac.setPBairro(jTextFieldPBairro.getText());
            pac.setPUf(jTextFieldPUf.getText());
            pac.setPCidade(jTextFieldPCidade.getText());
            pac.setPLogradouro(jTextFieldPendereco.getText());
            pac.setPNumero(Integer.parseInt(jTextFieldPNumero.getText()));
            pac.setPCompl(jTextFieldPComplemento.getText());
            pac.setPCep(jFormattedTextFieldPCep.getText());
            pac.setPDtNascimento(jFormattedTextFieldPDtNascimento.getText());
            pac.setPTelCelular(jFormattedTextFieldPTelCel.getText());
            pac.setPTelResidencial(jFormattedTextFieldPTelRes.getText());
            pac.setPEmail(jTextFieldPEmail.getText());
            pac.setPEmerNome(jTextFieldPEmerNome.getText());
            pac.setPEmerTelCelular(jFormattedTextFieldPEmerTelCel.getText());
            pac.setPEmerTelResidencial(jFormattedTextFieldPEmerTelRes1.getText());
            pac.setPCod(Integer.parseInt(jTextFieldPIdPaciente.getText()));

            controlP.Editar(pac);

            //Desaabilitar Campos tela cadastro Medico IDENFERMEIRO,NOME, COREN
            DesabilitarCampos();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar:!\n"
                    + "Verifique os dados informados no cadastro do paciente.");
        }
        DesabilitarCampos();

        jButtonBuscarCep.setEnabled(!true);
        jTextFieldPPesquisar.setEnabled(true);

        jButtonCancelar.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonIncluir.setEnabled(!false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        preencherTabelaPaciente("SELECT IDPACIENTE,NOMEPACIENTE,TELRESIDENCIAL,EMAIL,TELCELULAR FROM PACIENTE (NOLOCK) ORDER BY NOMEPACIENTE");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        flag = 2;

        jTextFieldPPesquisar.setText("");
        jButtonSalvar.setEnabled(true);
        jButtonBuscarCep.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonBuscarCep.setEnabled(true);

        HabilitarCampos();

    }//GEN-LAST:event_jButtonEditarActionPerformed
    public void preencherIdPacienteIncluir() {
        try {
            conBd.conectarBd();
            String sql = "SELECT MAX(IDPACIENTE+1) AS PROXID FROM PACIENTE (NOLOCK)";
            conBd.executaSql(sql);

            conBd.rs.first();

            jTextFieldPIdPaciente.setText(String.valueOf(conBd.rs.getInt("PROXID")));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar o proximo ID do usuário! " + ex.getMessage());
        }
        conBd.DesconectarBd();
    }
    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        // TODO add your handling code here:
        flag = 1;

        HabilitarCampos();
        preencherIdPacienteIncluir();
        jButtonBuscarCep.setEnabled(true);
        jTextFieldPPesquisar.setEnabled(true);

        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonBuscarCep.setEnabled(true);

    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jFormattedTextFieldPTelResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPTelResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPTelResActionPerformed

    private void jFormattedTextFieldPCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPCpfActionPerformed

    private void jFormattedTextFieldPRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPRgActionPerformed

    private void jButtonBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCepActionPerformed
        // TODO add your handling code here:
        WebServiceCep wsc = WebServiceCep.searchCep(jFormattedTextFieldPCep.getText());

        jTextFieldPendereco.setText(wsc.getLogradouro());
        jTextFieldPBairro.setText(wsc.getBairro());

        jTextFieldPCidade.setText(wsc.getCidade());
        jTextFieldPUf.setText(wsc.getUf());
    }//GEN-LAST:event_jButtonBuscarCepActionPerformed

    private void jButtonPPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPPesquisarActionPerformed
        // TODO add your handling code here:
        pac.setPesquisa(jTextFieldPPesquisar.getText());
        BeansPaciente pacien = controlP.buscaPaciente(pac);

        jButtonIncluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(false);

        preencherTabelaPaciente("SELECT IDPACIENTE,NOMEPACIENTE,TELRESIDENCIAL,TELCELULAR,EMAIL FROM PACIENTE (NOLOCK) WHERE NOMEPACIENTE LIKE '%" + pac.getPesquisa() + "%'");

    }//GEN-LAST:event_jButtonPPesquisarActionPerformed

    private void jTextFieldPIdPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPIdPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPIdPacienteActionPerformed

    private void jTextFieldPEmerNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPEmerNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPEmerNomeActionPerformed

    private void jButtonPPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPPesquisarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPPesquisarMouseClicked

    private void jTablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteMouseClicked
        // TODO add your handling code here:
        String idPaciente = "" + jTablePaciente.getValueAt(jTablePaciente.getSelectedRow(), 0);
        conBd.conectarBd();
        String sql = "SELECT IDPACIENTE,NOMEPACIENTE,RG,CPF,BAIRRO,ESTADO,CIDADE,LOGRADOURO,NUMERO,COMPL,"
                + "CEP,EMAIL,DATANASCIMENTO,TELRESIDENCIAL,TELCELULAR,CENOME,CETELCELULAR,CETELRESIDENCIAL"
                + " FROM PACIENTE (NOLOCK) WHERE IDPACIENTE = " + idPaciente;
        try {
            conBd.executaSql(sql);
            conBd.rs.first();

            LimparCampos();

            DesabilitarCampos();

            jTextFieldPIdPaciente.setText(String.valueOf(conBd.rs.getInt("IDPACIENTE")));
            jTextFieldPNome.setText(conBd.rs.getString("NOMEPACIENTE"));
            jFormattedTextFieldPRg.setText(conBd.rs.getString("RG"));
            jFormattedTextFieldPCpf.setText(conBd.rs.getString("CPF"));
            jTextFieldPBairro.setText(conBd.rs.getString("BAIRRO"));
            jTextFieldPUf.setText(conBd.rs.getString("ESTADO"));
            jTextFieldPCidade.setText(conBd.rs.getString("CIDADE"));
            jTextFieldPendereco.setText(conBd.rs.getString("LOGRADOURO"));
            jTextFieldPNumero.setText(String.valueOf(conBd.rs.getInt("NUMERO")));
            jTextFieldPComplemento.setText(conBd.rs.getString("COMPL"));
            jFormattedTextFieldPCep.setText(conBd.rs.getString("CEP"));
            jTextFieldPEmail.setText(conBd.rs.getString("EMAIL"));
            jFormattedTextFieldPDtNascimento.setText(conBd.rs.getString("DATANASCIMENTO"));
            jFormattedTextFieldPTelRes.setText(conBd.rs.getString("TELRESIDENCIAL"));
            jFormattedTextFieldPTelCel.setText(conBd.rs.getString("TELCELULAR"));
            jTextFieldPEmerNome.setText(conBd.rs.getString("CENOME"));
            jFormattedTextFieldPEmerTelCel.setText(conBd.rs.getString("CETELCELULAR"));
            jFormattedTextFieldPEmerTelRes1.setText(conBd.rs.getString("CETELRESIDENCIAL"));
            jButtonExcluir.setEnabled(true);
            jTextFieldPPesquisar.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao selecionar os dados" + ex.getMessage());
        }
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonBuscarCep.setEnabled(false);
        conBd.DesconectarBd();
    }//GEN-LAST:event_jTablePacienteMouseClicked

    public void LimparCampos() {
        jTextFieldPIdPaciente.setText("");
        jTextFieldPNome.setText("");
        jFormattedTextFieldPRg.setText("");
        jFormattedTextFieldPCpf.setText("");
        jTextFieldPendereco.setText("");
        jTextFieldPCidade.setText("");
        jFormattedTextFieldPDtNascimento.setText("");
        jTextFieldPBairro.setText("");
        jTextFieldPUf.setText("");
        jTextFieldPNumero.setText("");
        jFormattedTextFieldPTelRes.setText("");
        jFormattedTextFieldPTelCel.setText("");
        jFormattedTextFieldPCep.setText("");
        jTextFieldPComplemento.setText("");
        jTextFieldPEmail.setText("");
        jTextFieldPPesquisar.setText("");
        //COntato 
        jTextFieldPEmerNome.setText("");
        jFormattedTextFieldPEmerTelCel.setText("");
        jFormattedTextFieldPEmerTelRes1.setText("");
    }

    public void HabilitarCampos() {

        jTextFieldPNome.setEnabled(true);
        jFormattedTextFieldPRg.setEnabled(true);
        jFormattedTextFieldPCpf.setEnabled(true);
        jTextFieldPendereco.setEnabled(true);
        jTextFieldPCidade.setEnabled(true);
        jFormattedTextFieldPDtNascimento.setEnabled(true);
        jTextFieldPBairro.setEnabled(true);
        jTextFieldPUf.setEnabled(true);
        jTextFieldPNumero.setEnabled(true);
        jFormattedTextFieldPTelRes.setEnabled(true);
        jFormattedTextFieldPTelCel.setEnabled(true);
        jFormattedTextFieldPCep.setEnabled(true);
        jTextFieldPComplemento.setEnabled(true);
        jTextFieldPEmail.setEnabled(true);

        //Contato 
        jTextFieldPEmerNome.setEnabled(true);
        jFormattedTextFieldPEmerTelCel.setEnabled(true);
        jFormattedTextFieldPEmerTelRes1.setEnabled(true);
    }

    public void DesabilitarCampos() {
        jTextFieldPIdPaciente.setEnabled(false);
        jTextFieldPNome.setEnabled(false);
        jFormattedTextFieldPRg.setEnabled(false);
        jFormattedTextFieldPCpf.setEnabled(false);
        jTextFieldPendereco.setEnabled(false);
        jTextFieldPCidade.setEnabled(false);
        jFormattedTextFieldPDtNascimento.setEnabled(false);
        jTextFieldPBairro.setEnabled(false);
        jTextFieldPUf.setEnabled(false);
        jTextFieldPNumero.setEnabled(false);
        jFormattedTextFieldPTelRes.setEnabled(false);
        jFormattedTextFieldPTelCel.setEnabled(false);
        jFormattedTextFieldPCep.setEnabled(false);
        jTextFieldPComplemento.setEnabled(false);
        jTextFieldPEmail.setEnabled(false);

        //COntato 
        jTextFieldPEmerNome.setEnabled(false);
        jFormattedTextFieldPEmerTelCel.setEnabled(false);
        jFormattedTextFieldPEmerTelRes1.setEnabled(false);
    }

    private void preencherTabelaPaciente(String sql) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "NOME", "TEL.RESIDENCIAL", "TEL.CELULAR", "EMAIL"};

        conBd.conectarBd();

        conBd.executaSql(sql);
        try {
            conBd.rs.first();
            do {
                dados.add(new Object[]{
                    conBd.rs.getInt("IDPACIENTE"), conBd.rs.getString("NOMEPACIENTE"), conBd.rs.getString("TELRESIDENCIAL"),
                    conBd.rs.getString("TELCELULAR"), conBd.rs.getString("EMAIL")
                }
                );
            } while (conBd.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar os dados da tabela." + ex.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTablePaciente.setModel(modelo);

        jTablePaciente.getColumnModel().getColumn(0).setPreferredWidth(40);//Tamanho da tabela
        jTablePaciente.getColumnModel().getColumn(0).setResizable(false);

        jTablePaciente.getColumnModel().getColumn(1).setPreferredWidth(225);
        jTablePaciente.getColumnModel().getColumn(1).setResizable(false);

        jTablePaciente.getColumnModel().getColumn(2).setPreferredWidth(110);
        jTablePaciente.getColumnModel().getColumn(2).setResizable(false);

        jTablePaciente.getColumnModel().getColumn(3).setPreferredWidth(110);
        jTablePaciente.getColumnModel().getColumn(3).setResizable(false);

        jTablePaciente.getColumnModel().getColumn(4).setPreferredWidth(220);
        jTablePaciente.getColumnModel().getColumn(4).setResizable(false);

        jTablePaciente.getTableHeader().setReorderingAllowed(false);//reorganizar o cabeçalho
        jTablePaciente.setAutoResizeMode(jTablePaciente.AUTO_RESIZE_OFF); //NÃO VAI PODER REDIMENCIONAR A TABELA
        jTablePaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selecionar um por vez 
        //total do tamanho dos campos = 38 + 237 + 110 + 65 = 450
        conBd.DesconectarBd();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarCep;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonPPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldPCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldPCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldPDtNascimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldPEmerTelCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldPEmerTelRes1;
    private javax.swing.JFormattedTextField jFormattedTextFieldPRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldPTelCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldPTelRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField jTextFieldPBairro;
    private javax.swing.JTextField jTextFieldPCidade;
    private javax.swing.JTextField jTextFieldPComplemento;
    private javax.swing.JTextField jTextFieldPEmail;
    private javax.swing.JTextField jTextFieldPEmerNome;
    private javax.swing.JTextField jTextFieldPIdPaciente;
    private javax.swing.JTextField jTextFieldPNome;
    private javax.swing.JTextField jTextFieldPNumero;
    private javax.swing.JTextField jTextFieldPPesquisar;
    private javax.swing.JTextField jTextFieldPUf;
    private javax.swing.JTextField jTextFieldPendereco;
    // End of variables declaration//GEN-END:variables
}
