/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import ModeloBeans.ModeloTabela;
import ModeloConection.ConexaoBd;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Daniel Lucas
 */
public class FormConsultaRetorno extends javax.swing.JFrame {

     ConexaoBd conBd = new ConexaoBd();
     
    public String idConsultaRetorno;
    
    public FormConsultaRetorno() {
      
  }
     
    /**
     * Creates new form FormConsultaRetorno
     */
    public FormConsultaRetorno(Integer idPaciente) {
        initComponents();
        
        preencherTabelaAgendamento(
        "SELECT AGENDAMENTO.IDAGENDAMENTO,PACIENTE.NOMEPACIENTE,MEDICO.NOMEMEDICO,ESPECIALIDADE.ESPEC,AGENDAMENTO.DTAGENDAMENTO "+
        "FROM AGENDAMENTO " +
        "INNER JOIN ESPECIALIDADE ON AGENDAMENTO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE " +
        "INNER JOIN MEDICO ON MEDICO.IDMEDICO = AGENDAMENTO.IDMEDICO " +
        "INNER JOIN PACIENTE ON PACIENTE.IDPACIENTE =  AGENDAMENTO.IDPACIENTE "+        
        "WHERE DTAGENDAMENTO BETWEEN DATEADD(DAY, -30 , GETDATE()) "+
        "AND getdate() AND PACIENTE.IDPACIENTE = "+idPaciente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaRetorno = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filtro de consulta.");

        jTableConsultaRetorno.setBorder(new javax.swing.border.MatteBorder(null));
        jTableConsultaRetorno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableConsultaRetorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaRetornoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultaRetorno);

        jToggleButton1.setText("Selecionar Consulta de Retorno.");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Cancelar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jToggleButton1)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(710, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
         FormAgendamento formAgendamento = new FormAgendamento();
         
         formAgendamento.IdConsultaRetorno(String.valueOf(idConsultaRetorno));
       
         dispose();

    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    private void jTableConsultaRetornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaRetornoMouseClicked
        // TODO add your handling code here:
       
         idConsultaRetorno = "" + jTableConsultaRetorno.getValueAt(jTableConsultaRetorno.getSelectedRow(), 0);
       
    }//GEN-LAST:event_jTableConsultaRetornoMouseClicked

    
    
    
      public void preencherTabelaAgendamento(String sql) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"NUM","NOME PACIENTE" ,"NOME DO MEDICO", "ESPECIALIDADE", "CONSULTA"};

        conBd.conectarBd();

        conBd.executaSql(sql);
        try {
            conBd.rs.first();
            do {
                dados.add(new Object[]{
                    conBd.rs.getInt("IDAGENDAMENTO"), conBd.rs.getString("NOMEPACIENTE"), conBd.rs.getString("NOMEMEDICO"), conBd.rs.getString("ESPEC"),
                    conBd.rs.getString("DTAGENDAMENTO")}
                );
            } while (conBd.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar os dados da consulta anterior." + ex);
        }
 
          ModeloTabela modelo = new ModeloTabela(dados, colunas);
          jTableConsultaRetorno.setModel(modelo);

          //jTableConsultaRetorno.getColumnModel().getColumn(0).setPreferredWidth(110);//Tamanho da tabela
          jTableConsultaRetorno.getColumnModel().getColumn(0).setPreferredWidth(45);
          jTableConsultaRetorno.getColumnModel().getColumn(0).setResizable(false);

          jTableConsultaRetorno.getColumnModel().getColumn(1).setPreferredWidth(225);
          jTableConsultaRetorno.getColumnModel().getColumn(1).setResizable(false);
          
           jTableConsultaRetorno.getColumnModel().getColumn(2).setPreferredWidth(225);
          jTableConsultaRetorno.getColumnModel().getColumn(2).setResizable(false);

          jTableConsultaRetorno.getColumnModel().getColumn(3).setPreferredWidth(105);
          jTableConsultaRetorno.getColumnModel().getColumn(3).setResizable(false);

          jTableConsultaRetorno.getColumnModel().getColumn(4).setPreferredWidth(78);
          jTableConsultaRetorno.getColumnModel().getColumn(4).setResizable(false);
      

        jTableConsultaRetorno.getTableHeader().setReorderingAllowed(false);//reorganizar o cabeçalho
        jTableConsultaRetorno.setAutoResizeMode(jTableConsultaRetorno.AUTO_RESIZE_OFF); //NÃO VAI PODER REDIMENCIONAR A TABELA
        jTableConsultaRetorno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selecionar um por vez 
        //total do tamanho dos campos = 38 + 237 + 110 + 65 = 450
        conBd.DesconectarBd();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaRetorno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultaRetorno;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
