/*
 * 
 * buscar dados do correios CEP
 *http://respostas.guj.com.br/6592-api-java-para-buscar-cep-correios
 *https://viacep.com.br/
 */
package visao;

import ModeloConection.ConexaoBd;
import ModeloConection.WebServiceCep;
import ModeloDao.DaoEnfermeiro;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import ModeloBeans.BeansEnfermeiro;
import ModeloBeans.ModeloTabela;

/**
 *
 * @author Daniel Lucas
 */
public class FormEnfermeiro extends javax.swing.JFrame {

    ConexaoBd conBd = new ConexaoBd();
    BeansEnfermeiro enf = new BeansEnfermeiro();
    DaoEnfermeiro controlM = new DaoEnfermeiro();

    ResultSet rs = null;
    PreparedStatement pstM;
    // private final String SQLTABLE = "SELECT IDENFEMEIRO,NOMENOMEENFERMEIRO, COREN FROM ENFERMEIRO ORDER BY NOMENOMEENFERMEIRO";
    private int flag = 0;

    /**
     * Creates new form FormMedico
     */
    public FormEnfermeiro() {
        initComponents();
        preencherTabelaEnfermeiro("SELECT IDENFERMEIRO,NOMEENFERMEIRO, COREN FROM ENFERMEIRO ORDER BY NOMEENFERMEIRO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT enfify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMNome = new javax.swing.JLabel();
        jLabelMCrm = new javax.swing.JLabel();
        jLabelMCpf = new javax.swing.JLabel();
        jLabelMTelCel = new javax.swing.JLabel();
        jLabelMEndereco = new javax.swing.JLabel();
        jLabelMTelRes = new javax.swing.JLabel();
        jLabelMNumero = new javax.swing.JLabel();
        jLabelMRg = new javax.swing.JLabel();
        jFormattedTextFieldCoren = new javax.swing.JFormattedTextField();
        jTextFieldNomeEnfermeiro = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEnfermeiro = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jLabelMBairro = new javax.swing.JLabel();
        JlabelMCep = new javax.swing.JLabel();
        jLabelMComplemento = new javax.swing.JLabel();
        jTextFieldCompl = new javax.swing.JTextField();
        jButtonBuscarCep = new javax.swing.JButton();
        jLabelMUf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDEnfermeiro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldUF = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelResidencial = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelCelular = new javax.swing.JFormattedTextField();
        jLabelCadMedicos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabelMNome.setText("Nome: ");

        jLabelMCrm.setText("COREN:");

        jLabelMCpf.setText("CPF:");

        jLabelMTelCel.setText("TEL.CEL:");

        jLabelMEndereco.setText("Endereço");

        jLabelMTelRes.setText("TEL.RES:");

        jLabelMNumero.setText("Nº");

        jLabelMRg.setText("RG:");

        jFormattedTextFieldCoren.setEnabled(false);
        jFormattedTextFieldCoren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCorenActionPerformed(evt);
            }
        });

        jTextFieldNomeEnfermeiro.setToolTipText("medico.nome");
        jTextFieldNomeEnfermeiro.setEnabled(false);
        jTextFieldNomeEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeEnfermeiroActionPerformed(evt);
            }
        });

        jTextFieldEndereco.setEnabled(false);

        jTextFieldNumero.setEnabled(false);
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableEnfermeiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEnfermeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEnfermeiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEnfermeiro);

        jTextFieldPesquisa.setToolTipText("");
        jTextFieldPesquisa.setOpaque(true);

        jButtonPesquisa.setText("Pesquisa");
        jButtonPesquisa.setOpaque(true);
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });
        jButtonPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonPesquisaKeyPressed(evt);
            }
        });

        jLabelMBairro.setText("Bairro:");

        JlabelMCep.setText("CEP :");

        jLabelMComplemento.setText("Complemento:");

        jTextFieldCompl.setEnabled(false);

        jButtonBuscarCep.setText("Buscar");
        jButtonBuscarCep.setEnabled(false);
        jButtonBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCepActionPerformed(evt);
            }
        });

        jLabelMUf.setText("UF:");

        jLabel1.setText("ID Enfermeiro: ");

        jTextFieldIDEnfermeiro.setEnabled(false);

        jLabel2.setText("Cidade:");

        jTextFieldBairro.setEnabled(false);
        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jTextFieldUF.setEnabled(false);

        jTextFieldCidade.setEnabled(false);

        jLabel3.setText("E-mail:");

        jTextFieldEmail.setEnabled(false);

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.setEnabled(false);

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf.setEnabled(false);

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRg.setEnabled(false);

        try {
            jFormattedTextFieldTelResidencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelResidencial.setEnabled(false);

        try {
            jFormattedTextFieldTelCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelCelular.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMCrm)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldCoren, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCompl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIDEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMEndereco)
                                    .addComponent(jLabelMUf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMNome)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JlabelMCep)
                                        .addComponent(jLabelMBairro)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonBuscarCep)
                                            .addGap(84, 84, 84)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldNomeEnfermeiro)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelMNumero)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelMTelCel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelMTelRes, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelMCpf)
                                            .addComponent(jLabelMRg))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldTelResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIDEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNomeEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMEndereco)
                            .addComponent(jLabelMNumero)
                            .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMBairro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMUf)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscarCep)
                            .addComponent(JlabelMCep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMComplemento)
                                    .addComponent(jTextFieldCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMCrm)
                                    .addComponent(jFormattedTextFieldCoren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPesquisa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMRg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMTelCel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTelResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMTelRes))))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabelCadMedicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCadMedicos.setText("Cadastro de Enfermeiro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabelCadMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1118, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jButtonBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCepActionPerformed
        // TODO add your handling code here:
        WebServiceCep wsc = WebServiceCep.searchCep(jFormattedTextFieldCep.getText());

        jTextFieldEndereco.setText(wsc.getLogradouro());
        jTextFieldBairro.setText(wsc.getBairro());

        jTextFieldCidade.setText(wsc.getCidade());
        jTextFieldUF.setText(wsc.getUf());

        // https://viacep.com.br/ webservices correios
        // http://www.devmedia.com.br/atualizacao-devmedia-apis-do-cep-inclusao-do-codigo-ibge-e-o-campo-logradouro-curto-nos-retornos/30172
    }//GEN-LAST:event_jButtonBuscarCepActionPerformed

    private void jButtonPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPesquisaKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPesquisaKeyPressed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        // TODO add your handling code here:

        enf.setEPesquisa(jTextFieldPesquisa.getText());
        ModeloBeans.BeansEnfermeiro enfel = controlM.buscaEnfermeiro(enf);

        jButtonIncluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);

        jTextFieldIDEnfermeiro.setText(String.valueOf(enfel.getECod()));
        jTextFieldNomeEnfermeiro.setText(enfel.getENome());
        jTextFieldEndereco.setText(enfel.getELogradouro());
        jTextFieldNumero.setText(String.valueOf(enfel.getENumero()));
        jTextFieldBairro.setText(enfel.getEBairro());
        jTextFieldCidade.setText(enfel.getECidade());
        jTextFieldUF.setText(enfel.getESUf());
        jTextFieldEmail.setText(enfel.getEEmail());
        jFormattedTextFieldCpf.setText(enfel.getECpf());
        jFormattedTextFieldRg.setText(enfel.getERg());
        jFormattedTextFieldTelResidencial.setText(enfel.getETelResidencial());
        jFormattedTextFieldTelCelular.setText(enfel.getETelCelular());
        jFormattedTextFieldCoren.setText(enfel.getECoren());
        jFormattedTextFieldCep.setText(enfel.getECep());
        jTextFieldCompl.setText(enfel.getECompl());
        preencherTabelaEnfermeiro("SELECT IDENFERMEIRO,NOMEENFERMEIRO, COREN FROM ENFERMEIRO WHERE NOMEENFERMEIRO like '%" + enf.getEPesquisa() + "%'");
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jTableEnfermeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEnfermeiroMouseClicked

        // TODO add your handling code here:
        String Nome = "" + jTableEnfermeiro.getValueAt(jTableEnfermeiro.getSelectedRow(), 1);
        conBd.conectarBd();
        try {
            String sql = "select * from ENFERMEIRO where nomeENFERMEIRO = '" + Nome + "'";
            conBd.executaSql(sql);
            conBd.rs.first();
            LimparCampos();
            DesabilitarCampos();
            jTextFieldIDEnfermeiro.setText(String.valueOf(conBd.rs.getInt("IDENFERMEIRO")));
            jTextFieldNomeEnfermeiro.setText(conBd.rs.getString("NOMEENFERMEIRO"));
            jTextFieldEndereco.setText(conBd.rs.getString("LOGRADOURO"));
            jTextFieldNumero.setText(String.valueOf(conBd.rs.getInt("NUMERO")));
            jTextFieldBairro.setText(conBd.rs.getString("BAIRRO"));
            jFormattedTextFieldCpf.setText(conBd.rs.getString("CPF"));
            jFormattedTextFieldRg.setText(conBd.rs.getString("RG"));
            jFormattedTextFieldTelResidencial.setText(conBd.rs.getString("TELRESIDENCIAL"));
            jFormattedTextFieldTelCelular.setText(conBd.rs.getString("TELCELULAR"));
            jFormattedTextFieldCoren.setText(conBd.rs.getString("COREN"));
            jFormattedTextFieldCep.setText(conBd.rs.getString("CEP"));
            jTextFieldCompl.setText(conBd.rs.getString("COMPL"));
            jTextFieldCidade.setText(conBd.rs.getString("CIDADE"));
            jTextFieldUF.setText(conBd.rs.getString("ESTADO"));
            jTextFieldEmail.setText(conBd.rs.getString("EMAIL"));
            jTextFieldPesquisa.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro ao selecionar os dados" + ex.getMessage());
        }
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        conBd.DesconectarBd();
    }//GEN-LAST:event_jTableEnfermeiroMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:

        //Limpar os campos
        LimparCampos();

        //Habilitar ou Desabilitar Campos
        DesabilitarCampos();
        jButtonBuscarCep.setEnabled(!true);
        jTextFieldPesquisa.setEnabled(true);
        jButtonCancelar.setEnabled(!true);
        jButtonIncluir.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisa.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir? ");
        if (resposta == JOptionPane.YES_OPTION) {
            enf.setECod(Integer.parseInt(jTextFieldIDEnfermeiro.getText()));
            controlM.Excluir(enf);
            preencherTabelaEnfermeiro("SELECT IDENFERMEIRO,NOMEENFERMEIRO, COREN FROM ENFERMEIRO ORDER BY NOMEENFERMEIRO");

            jButtonSalvar.setEnabled(!true);
            jButtonBuscarCep.setEnabled(true);
            jButtonCancelar.setEnabled(!true);
            jButtonIncluir.setEnabled(true);
            jButtonExcluir.setEnabled(false);

            LimparCampos();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (jTextFieldNomeEnfermeiro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o NOME para continuar.");
            jTextFieldNomeEnfermeiro.requestFocus();
        } else if (jFormattedTextFieldCoren.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o COREN para continuar.");
            jFormattedTextFieldCoren.requestFocus();
        }

        if (flag == 1) {
            //Ler campos da tela de cadastro do medico

            enf.setENome(jTextFieldNomeEnfermeiro.getText());
            enf.setECpf(jFormattedTextFieldCpf.getText());
            enf.setERg(jFormattedTextFieldRg.getText());
            enf.setETelCelular(jFormattedTextFieldTelCelular.getText());
            enf.setETelResidencial(jFormattedTextFieldTelResidencial.getText());
            enf.setELogradouro(jTextFieldEndereco.getText());
            enf.setEBairro(jTextFieldBairro.getText());
            enf.setENumero(Integer.parseInt(jTextFieldNumero.getText()));
            enf.setECoren((jFormattedTextFieldCoren.getText()));
            enf.setECep(jFormattedTextFieldCep.getText());
            enf.setECidade(jTextFieldCidade.getText());
            enf.setESUf(jTextFieldUF.getText());
            enf.setECompl(jTextFieldCompl.getText());
            enf.setEEmail(jTextFieldEmail.getText());
            controlM.salvar(enf);

            preencherTabelaEnfermeiro("SELECT IDENFERMEIRO,NOMEENFERMEIRO, COREN FROM ENFERMEIRO ORDER BY NOMEENFERMEIRO");
            //Limpar os campos
            LimparCampos();

            DesabilitarCampos();

        } else {
            flag = 2;

            enf.setECod((Integer.parseInt(jTextFieldIDEnfermeiro.getText())));
            enf.setENome(jTextFieldNomeEnfermeiro.getText());
            enf.setECpf(jFormattedTextFieldCpf.getText());
            enf.setERg(jFormattedTextFieldRg.getText());
            enf.setETelCelular(jFormattedTextFieldTelCelular.getText());
            enf.setETelResidencial(jFormattedTextFieldTelResidencial.getText());
            enf.setELogradouro(jTextFieldEndereco.getText());
            enf.setEBairro(jTextFieldBairro.getText());
            enf.setENumero(Integer.parseInt(jTextFieldNumero.getText()));
            enf.setECoren((jFormattedTextFieldCoren.getText()));
            enf.setECep(jFormattedTextFieldCep.getText());
            enf.setECompl(jTextFieldCompl.getText());
            enf.setECidade(jTextFieldCidade.getText());
            enf.setESUf(jTextFieldUF.getText());
            enf.setEEmail(jTextFieldEmail.getText());

            controlM.Editar(enf);
            preencherTabelaEnfermeiro("SELECT * FROM ENFERMEIRO ORDER BY NOMEENFERMEIRO");

            //Desaabilitar Campos tela cadastro Medico IDENFERMEIRO,NOME, COREN
            DesabilitarCampos();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed
    public void preencherIdEnfermeiroIncluir() {
        try {
            conBd.conectarBd();
            String sql = "SELECT MAX(IDENFERMEIRO+1) AS PROXID FROM ENFERMEIRO";
            conBd.executaSql(sql);

            conBd.rs.first();

            jTextFieldIDEnfermeiro.setText(String.valueOf(conBd.rs.getInt("PROXID")));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar o proximo ID do usuário! " + ex.getMessage());
        }
        conBd.DesconectarBd();
    }
    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed

        flag = 1;
        //Limpar os campos
        LimparCampos();
        preencherIdEnfermeiroIncluir();
        HabilitarCampos();
        jButtonBuscarCep.setEnabled(true);
        jTextFieldPesquisa.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:

        flag = 2;
        jTextFieldPesquisa.setText("");
        jButtonSalvar.setEnabled(true);
        jButtonBuscarCep.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        HabilitarCampos();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jTextFieldNomeEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeEnfermeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeEnfermeiroActionPerformed

    private void jFormattedTextFieldCorenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCorenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCorenActionPerformed

    public void HabilitarCampos() {
        jButtonSalvar.setEnabled(!false);
        jButtonBuscarCep.setEnabled(!false);

        jTextFieldBairro.setEnabled(!false);
        jTextFieldEndereco.setEnabled(!false);
        jTextFieldNomeEnfermeiro.setEnabled(!false);
        jTextFieldNumero.setEnabled(!false);
        jTextFieldUF.setEnabled(!false);
        jFormattedTextFieldCep.setEnabled(!false);
        jTextFieldCompl.setEnabled(!false);
        jTextFieldCidade.setEnabled(!false);
        jTextFieldEmail.setEnabled(!false);

        jFormattedTextFieldCpf.setEnabled(!false);
        jFormattedTextFieldCoren.setEnabled(!false);
        jFormattedTextFieldRg.setEnabled(!false);
        jFormattedTextFieldTelCelular.setEnabled(!false);
        jFormattedTextFieldTelResidencial.setEnabled(!false);
    }

    public void DesabilitarCampos() {
        jButtonSalvar.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldNomeEnfermeiro.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jTextFieldUF.setEnabled(false);
        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldCoren.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelCelular.setEnabled(false);
        jFormattedTextFieldTelResidencial.setEnabled(false);
        jFormattedTextFieldCep.setEnabled(false);
        jTextFieldCompl.setEnabled(false);
        jButtonBuscarCep.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldEmail.setEnabled(false);

    }

    public void LimparCampos() {

        jTextFieldPesquisa.setText("");
        jTextFieldBairro.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNomeEnfermeiro.setText("");
        jTextFieldNumero.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldCoren.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelCelular.setText("");
        jFormattedTextFieldTelResidencial.setText("");
        jFormattedTextFieldCep.setText("");
        jTextFieldCompl.setText("");
        jTextFieldIDEnfermeiro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldUF.setText("");
        jTextFieldEmail.setText("");

    }

    @SuppressWarnings("unchecked")
    public final void preencherTabelaEnfermeiro(String sql) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "NOME", "COREN"};
        conBd.conectarBd();

        conBd.executaSql(sql);

        try {
            conBd.rs.first();
            do {
                dados.add(new Object[]{conBd.rs.getInt("IDENFERMEIRO"), conBd.rs.getString("NOMEENFERMEIRO"), conBd.rs.getInt("COREN")});

            } while (conBd.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Busque por outro ENFERMEIRO para preencher tabela.");
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableEnfermeiro.setModel(modelo);

        jTableEnfermeiro.getColumnModel().getColumn(0).setPreferredWidth(30);//Tamanho da tabela
        jTableEnfermeiro.getColumnModel().getColumn(0).setResizable(false);

        jTableEnfermeiro.getColumnModel().getColumn(1).setPreferredWidth(220);
        jTableEnfermeiro.getColumnModel().getColumn(1).setResizable(false);

        jTableEnfermeiro.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTableEnfermeiro.getColumnModel().getColumn(2).setResizable(false);

        jTableEnfermeiro.getTableHeader().setReorderingAllowed(false);//reorganizar o cabeçalho
        jTableEnfermeiro.setAutoResizeMode(jTableEnfermeiro.AUTO_RESIZE_OFF); //NÃO VAI PODER REDIMENCIONAR A TABELA
        jTableEnfermeiro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selecionar um por vez 

        conBd.DesconectarBd();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEnfermeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelMCep;
    private javax.swing.JButton jButtonBuscarCep;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldCoren;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelResidencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadMedicos;
    private javax.swing.JLabel jLabelMBairro;
    private javax.swing.JLabel jLabelMComplemento;
    private javax.swing.JLabel jLabelMCpf;
    private javax.swing.JLabel jLabelMCrm;
    private javax.swing.JLabel jLabelMEndereco;
    private javax.swing.JLabel jLabelMNome;
    private javax.swing.JLabel jLabelMNumero;
    private javax.swing.JLabel jLabelMRg;
    private javax.swing.JLabel jLabelMTelCel;
    private javax.swing.JLabel jLabelMTelRes;
    private javax.swing.JLabel jLabelMUf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEnfermeiro;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCompl;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldIDEnfermeiro;
    private javax.swing.JTextField jTextFieldNomeEnfermeiro;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldUF;
    // End of variables declaration//GEN-END:variables
}
