package Visao;

import ModeloBeans.BeansDadosUsuario;
import ModeloConection.ConexaoBd;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import ModeloDao.DaoCripSenhaUser;
import ModeloDao.DaoAlias;
import ModeloDao.DaoProfilerBancoDados;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * @author Daniel Lucas
 */
public class FormTelaLogin extends javax.swing.JFrame {

    ConexaoBd con = new ConexaoBd();
    String nome, senhaEmail, email, smtp, usuario;
    Integer porta;

    /**
     * Creates new form visão
     */
    public FormTelaLogin() {
        initComponents();
        preencherAliasBD();
        // con.conectarBd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAcessar = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        BtnLoginAutomatico = new javax.swing.JToggleButton();
        jLabelSenhaUsuario = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldUsuario = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButtonBancoDados = new javax.swing.JButton();
        jchoiceBancoDados = new java.awt.Choice();
        JLTelaLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Clinica Medica");
        setUndecorated(true);
        getContentPane().setLayout(null);

        BtnAcessar.setText("Acessar");
        BtnAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAcessarActionPerformed(evt);
            }
        });
        BtnAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAcessarKeyPressed(evt);
            }
        });
        getContentPane().add(BtnAcessar);
        BtnAcessar.setBounds(250, 180, 80, 30);

        BtnSair.setText("Sair");
        BtnSair.setMaximumSize(new java.awt.Dimension(73, 28));
        BtnSair.setMinimumSize(new java.awt.Dimension(73, 28));
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSair);
        BtnSair.setBounds(340, 180, 80, 30);

        BtnLoginAutomatico.setText("Login Automático");
        BtnLoginAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginAutomaticoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLoginAutomatico);
        BtnLoginAutomatico.setBounds(250, 220, 170, 28);

        jLabelSenhaUsuario.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabelSenhaUsuario.setText("Senha");
        getContentPane().add(jLabelSenhaUsuario);
        jLabelSenhaUsuario.setBounds(20, 110, 50, 30);

        jLabelUsuario.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabelUsuario.setText("Usuário");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(20, 60, 110, 21);
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(20, 80, 170, 28);

        jPasswordFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldUsuario);
        jPasswordFieldUsuario.setBounds(20, 140, 170, 28);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel1.setText("Banco de Dados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 180, 120, 21);

        jButtonBancoDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Bd.png"))); // NOI18N
        jButtonBancoDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBancoDadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBancoDados);
        jButtonBancoDados.setBounds(170, 210, 30, 30);

        jchoiceBancoDados.setName(""); // NOI18N
        jchoiceBancoDados.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jchoiceBancoDadosPropertyChange(evt);
            }
        });
        getContentPane().add(jchoiceBancoDados);
        jchoiceBancoDados.setBounds(20, 210, 140, 40);

        JLTelaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundotelaLogin.png"))); // NOI18N
        JLTelaLogin.setName(""); // NOI18N
        getContentPane().add(JLTelaLogin);
        JLTelaLogin.setBounds(-50, 0, 500, 270);

        setSize(new java.awt.Dimension(443, 264));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConectaSistema() {
        BeansDadosUsuario beansDadosUsuario = new BeansDadosUsuario();
        try {
            con.conectarBd();
            con.executaSql("SELECT NOME,USENHAEMAIL,EMAIL,UPORTASMTP,USERSAISMTP,"
                    + "SENHA FROM  USUARIO (NOLOCK) WHERE NOME ='"
                    + jTextFieldUsuario.getText() + "' AND ATIVO = 1");
            con.rs.first();
            String senha = new String(jPasswordFieldUsuario.getPassword());
            if (con.rs.getString("SENHA").equals(DaoCripSenhaUser.codificaBase64Encoder(senha))) {

                beansDadosUsuario.setEmail(con.rs.getString("EMAIL"));
                beansDadosUsuario.setNome(con.rs.getString("NOME"));
                beansDadosUsuario.setPortaSmtp(con.rs.getInt("UPORTASMTP"));
                beansDadosUsuario.setSenhaEmail(con.rs.getString("USENHAEMAIL"));
                beansDadosUsuario.setSmtp(con.rs.getString("USERSAISMTP"));

                FormTelaPrincipal tela = new FormTelaPrincipal(beansDadosUsuario);

                tela.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Senha não confere", nome, JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao realizar o login no sistema!\n"
                    + "Usuário/Senha inválido ou não cadastrado no sistema! \n Erro:" + ex, "Falha Inesperada.",
                    JOptionPane.ERROR_MESSAGE);
            jPasswordFieldUsuario.setText("");
        }
    }

    private void BtnAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAcessarActionPerformed

        ConectaSistema();

    }//GEN-LAST:event_BtnAcessarActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_BtnSairActionPerformed

    private void jPasswordFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldUsuarioActionPerformed
    }//GEN-LAST:event_jPasswordFieldUsuarioActionPerformed

    private void BtnAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAcessarKeyPressed
        // TODO add your handling code here:
//        if (evt.getKeyCode() == evt.VK_ENTER) {
//            try {
//                con.executaSql("SELECT * FROM USUARIO WHERE NOME ='" + jTextFieldUsuario.getText() + "'");
//                con.rs.first();
//
//                if (con.rs.getString("SENHA").equals(DaoCripSenhaUser.codificaBase64Encoder(jPasswordFieldUsuario.getText()))) {
//                    //  FormTelaPrincipal tela = new FormTelaPrincipal(jTextFieldUsuario.getText());
//
//                    // tela.setVisible(true);
//                    dispose();
//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Usuário/Senha inválido ou não cadastrado no sistema!");
//                }
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(rootPane, "Usuário/Senha inválido ou não cadastrado no sistema!\nErro:" + ex);
//            }
//            con.DesconectarBd();
//        }
    }//GEN-LAST:event_BtnAcessarKeyPressed

    private void jButtonBancoDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBancoDadosActionPerformed
        //FormAlias bd = new FormAlias();
        FormAliasAlterado bd = new FormAliasAlterado();
        bd.setVisible(true);
    }//GEN-LAST:event_jButtonBancoDadosActionPerformed

    private void jchoiceBancoDadosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jchoiceBancoDadosPropertyChange
        preencherAliasBD();
    }//GEN-LAST:event_jchoiceBancoDadosPropertyChange

    private void BtnLoginAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginAutomaticoActionPerformed

        jTextFieldUsuario.setText("Adm");
        jPasswordFieldUsuario.setText("12345");
        
        ConectaSistema();
    }//GEN-LAST:event_BtnLoginAutomaticoActionPerformed
    public final void preencherAliasBD() {
        DaoAlias daoAlias = new DaoAlias();

        try {

            //cria um scanner para ler o arquivo
            Scanner leitor = new Scanner(daoAlias.file);
            //variavel que armazenara as linhas do arquivo
            String linhasDoArquivo = new String();
            //ignora a primeira linha do arquivo
            //  leitor.nextLine();
            //percorre todo o arquivo
            while (leitor.hasNext()) {
                //recebe cada linha do arquivo
                linhasDoArquivo = leitor.nextLine();
                //separa os campos entre as virgulas de cada linha
                String[] valoresEntreVirgulas = linhasDoArquivo.split(";");
                //imprime a coluna que quiser
                jchoiceBancoDados.add(valoresEntreVirgulas[0]);
            }
        } catch (FileNotFoundException fileNotFoundException) {
            System.out.println("teste4: " + fileNotFoundException.getMessage());
        }
    }
    
    public void HabilitaProfilerBD(boolean profiler){
        DaoProfilerBancoDados dados = new DaoProfilerBancoDados();
         dados.setProfilerBancoDados(profiler);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAcessar;
    private javax.swing.JToggleButton BtnLoginAutomatico;
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel JLTelaLogin;
    private javax.swing.JButton jButtonBancoDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSenhaUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldUsuario;
    private javax.swing.JTextField jTextFieldUsuario;
    private java.awt.Choice jchoiceBancoDados;
    // End of variables declaration//GEN-END:variables
}
