/*
*uscar dados do correios CEP
*https://sqlfromhell.wordpress.com/2009/11/28/valores-numericos-cpf-e-cnpj/
 *http://respostas.guj.com.br/6592-api-java-para-buscar-cep-correios
 *https://viacep.com.br/
 */
package Visao;

import ModeloBeans.BeansDadosUsuario;
import ModeloConection.ConexaoBd;
import ModeloConection.WebServiceCep;
import ModeloDao.DaoMedico;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import ModeloBeans.BeansMedico;
import ModeloBeans.ModeloTabela;
import ModeloDao.DaoEspecialidade;

/**
 *
 * @author Daniel Lucas
 */
public class FormMedico extends javax.swing.JFrame {

    ConexaoBd conBd = new ConexaoBd();
    BeansMedico mod = new BeansMedico();
    DaoMedico controlM = new DaoMedico();
    DaoEspecialidade DaoEspecialidade = new DaoEspecialidade();

    ResultSet rs = null;
    PreparedStatement pstM;
    int flag = 0;

    /**
     * Creates new form FormMedico
     */
    public FormMedico() {

    }

    public FormMedico(BeansDadosUsuario beansDadosUsuario) {
        initComponents();
        preencherTabelaMedico("SELECT IDMEDICO,NOMEMEDICO,ESPEC, CRM, MEDICO.ATIVO FROM MEDICO (NOLOCK)"
                + "INNER JOIN ESPECIALIDADE (NOLOCK) ON MEDICO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE ORDER BY NOMEMEDICO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMNome = new javax.swing.JLabel();
        jLabelMCrm = new javax.swing.JLabel();
        jLabelMCpf = new javax.swing.JLabel();
        jLabelMTelCel = new javax.swing.JLabel();
        jLabelMEndereco = new javax.swing.JLabel();
        jLabelMTelRes = new javax.swing.JLabel();
        jLabelMNumero = new javax.swing.JLabel();
        jLabelMRg = new javax.swing.JLabel();
        jLabelMEspecialidade = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCrm = new javax.swing.JFormattedTextField();
        jTextFieldNomeMed = new javax.swing.JTextField();
        jFormattedTextFieldTelCel = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelRes = new javax.swing.JFormattedTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jComboBoxEspecializacao = new javax.swing.JComboBox<>();
        jButtonEditar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMedicos = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jLabelMBairro = new javax.swing.JLabel();
        JlabelMCep = new javax.swing.JLabel();
        jLabelMComplemento = new javax.swing.JLabel();
        jTextFieldCompl = new javax.swing.JTextField();
        jButtonBuscarCep = new javax.swing.JButton();
        jLabelMUf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIDMedico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldUF = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jCheckBoxMedicoAtivo = new javax.swing.JCheckBox();
        jRadioButtonFiltroMedicoAtivo = new javax.swing.JRadioButton();
        jRadioButtonFiltroMedicoNaoAtivo = new javax.swing.JRadioButton();
        jRadioButtonFiltroMedicoTodosAtivo = new javax.swing.JRadioButton();
        jLabelCadMedicos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabelMNome.setText("Nome: ");

        jLabelMCrm.setText("CRM:");

        jLabelMCpf.setText("CPF:");

        jLabelMTelCel.setText("TEL.CEL");

        jLabelMEndereco.setText("Endereço");

        jLabelMTelRes.setText("TEL.RES");

        jLabelMNumero.setText("Nº");

        jLabelMRg.setText("RG:");

        jLabelMEspecialidade.setText("Especialização:");

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf.setEnabled(false);

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldRgActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCrm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########/UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCrm.setEnabled(false);
        jFormattedTextFieldCrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCrmActionPerformed(evt);
            }
        });

        jTextFieldNomeMed.setToolTipText("medico.nome");
        jTextFieldNomeMed.setEnabled(false);
        jTextFieldNomeMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeMedActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelCel.setEnabled(false);

        try {
            jFormattedTextFieldTelRes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelRes.setEnabled(false);
        jFormattedTextFieldTelRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelResActionPerformed(evt);
            }
        });

        jTextFieldEndereco.setEnabled(false);

        jTextFieldNumero.setEnabled(false);
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        jComboBoxEspecializacao.setEditable(true);
        jComboBoxEspecializacao.setEnabled(false);
        jComboBoxEspecializacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxEspecializacaoMouseClicked(evt);
            }
        });
        jComboBoxEspecializacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspecializacaoActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableMedicos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMedicos);

        jTextFieldPesquisa.setToolTipText("");
        jTextFieldPesquisa.setOpaque(true);

        jButtonPesquisa.setText("Pesquisa");
        jButtonPesquisa.setOpaque(true);
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });
        jButtonPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonPesquisaKeyPressed(evt);
            }
        });

        jLabelMBairro.setText("Bairro:");

        JlabelMCep.setText("CEP :");

        jLabelMComplemento.setText("Complemento:");

        jTextFieldCompl.setEnabled(false);

        jButtonBuscarCep.setText("Buscar");
        jButtonBuscarCep.setEnabled(false);
        jButtonBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCepActionPerformed(evt);
            }
        });

        jLabelMUf.setText("UF:");

        jLabel1.setText("ID Medico: ");

        jTextFieldIDMedico.setEnabled(false);

        jLabel2.setText("Cidade:");

        jTextFieldBairro.setEnabled(false);
        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });

        jTextFieldUF.setEnabled(false);

        jTextFieldCidade.setEnabled(false);

        jLabel3.setText("E-mail:");

        jTextFieldEmail.setEnabled(false);
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCEP.setEnabled(false);

        jCheckBoxMedicoAtivo.setText("Ativo");
        jCheckBoxMedicoAtivo.setEnabled(false);

        jRadioButtonFiltroMedicoAtivo.setText("Médicos Ativos");
        jRadioButtonFiltroMedicoAtivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonFiltroMedicoAtivoStateChanged(evt);
            }
        });
        jRadioButtonFiltroMedicoAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFiltroMedicoAtivoMouseClicked(evt);
            }
        });

        jRadioButtonFiltroMedicoNaoAtivo.setText("Médicos Não Ativos");
        jRadioButtonFiltroMedicoNaoAtivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonFiltroMedicoNaoAtivoStateChanged(evt);
            }
        });
        jRadioButtonFiltroMedicoNaoAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFiltroMedicoNaoAtivoMouseClicked(evt);
            }
        });

        jRadioButtonFiltroMedicoTodosAtivo.setText("Médicos Todos");
        jRadioButtonFiltroMedicoTodosAtivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonFiltroMedicoTodosAtivoStateChanged(evt);
            }
        });
        jRadioButtonFiltroMedicoTodosAtivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFiltroMedicoTodosAtivoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelMComplemento)
                            .addComponent(jTextFieldCompl, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMCrm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMEspecialidade)
                            .addComponent(jTextFieldEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonFiltroMedicoTodosAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonFiltroMedicoAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonFiltroMedicoNaoAtivo)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditar)
                .addGap(12, 12, 12)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluir)
                .addGap(12, 12, 12)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxMedicoAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMEndereco)
                                    .addComponent(jLabelMBairro)
                                    .addComponent(jLabelMNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldNomeMed))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMRg, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldRg)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(JlabelMCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscarCep)
                                .addGap(0, 376, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelMUf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelMTelRes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelMTelCel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldTelCel)))))
                .addGap(465, 465, 465))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jCheckBoxMedicoAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIDMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelMNome)
                    .addComponent(jTextFieldNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMCpf)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelMEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMNumero)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMRg)
                    .addComponent(jFormattedTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelMBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMTelRes)
                    .addComponent(jFormattedTextFieldTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jFormattedTextFieldTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMTelCel)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelMUf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCep)
                    .addComponent(JlabelMCep)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonFiltroMedicoNaoAtivo)
                        .addComponent(jRadioButtonFiltroMedicoAtivo)
                        .addComponent(jRadioButtonFiltroMedicoTodosAtivo))
                    .addComponent(jLabelMComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelMEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMCrm)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabelCadMedicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCadMedicos.setText("Cadastro de Médicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabelCadMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1118, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonFiltroMedicoNaoAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroMedicoNaoAtivoMouseClicked
        // TODO add your handling code here: if(jRadioButtonFiltroMedicoNaoAtivo.isSelected()){
//        if (jRadioButtonFiltroMedicoAtivo.isSelected()) {
//            jRadioButtonFiltroMedicoAtivo.setSelected(false);
//        }
//        if (jRadioButtonFiltroMedicoTodosAtivo.isSelected()) {
//            jRadioButtonFiltroMedicoTodosAtivo.setSelected(false);
//        }
    }//GEN-LAST:event_jRadioButtonFiltroMedicoNaoAtivoMouseClicked

    private void jRadioButtonFiltroMedicoAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroMedicoAtivoMouseClicked
        // TODO add your handling code here:
//        if(jRadioButtonFiltroMedicoNaoAtivo.isSelected()){
//            jRadioButtonFiltroMedicoNaoAtivo.setSelected(false);
//            jRadioButtonFiltroMedicoTodosAtivo.setSelected(false);
//        } 
//        if(jRadioButtonFiltroMedicoTodosAtivo.isSelected()){
//                jRadioButtonFiltroMedicoTodosAtivo.setSelected(false);
//        }
    }//GEN-LAST:event_jRadioButtonFiltroMedicoAtivoMouseClicked

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jButtonBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCepActionPerformed

        if (jFormattedTextFieldCEP.getText().replace("-", "").replace(" ", "").isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo CEP, encontra-se vazio, gentileza preencher com um valor válido");
            jFormattedTextFieldCEP.requestFocus();
            return;
        }
        WebServiceCep wsc = WebServiceCep.searchCep(jFormattedTextFieldCEP.getText());
        if (wsc.wasSuccessful() == false) {
            JOptionPane.showMessageDialog(null, "\r\t O Cep informado não existe na base de dados, sendo necessário "
                    + "informar os seguintes campos manualmente na tela de cadastro: \n Endereço - Bairro - UF - Cidade - CEP");
            return;
        }

        jTextFieldEndereco.setText(wsc.getLogradouro());
        jTextFieldBairro.setText(wsc.getBairro());

        jTextFieldCidade.setText(wsc.getCidade());
        jTextFieldUF.setText(wsc.getUf());

        // https://viacep.com.br/ webservices correios
        // http://www.devmedia.com.br/atualizacao-devmedia-apis-do-cep-inclusao-do-codigo-ibge-e-o-campo-logradouro-curto-nos-retornos/30172
    }//GEN-LAST:event_jButtonBuscarCepActionPerformed

    private void jButtonPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonPesquisaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisaKeyPressed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        // TODO add your handling code here:

        mod.setMPesquisa(jTextFieldPesquisa.getText());
        String sql = "SELECT IDMEDICO,NOMEMEDICO,ESPEC,CRM,MEDICO.ATIVO "
                + "FROM MEDICO (NOLOCK) "
                + "INNER JOIN ESPECIALIDADE (NOLOCK) "
                + "ON MEDICO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE "
                + "WHERE MEDICO.NOMEMEDICO LIKE '%" + mod.getMPesquisa() + "%'";

        if (jRadioButtonFiltroMedicoAtivo.isSelected()) {
            sql += " AND MEDICO.ATIVO = 1";
        }
        if (jRadioButtonFiltroMedicoNaoAtivo.isSelected()) {
            sql += " AND MEDICO.ATIVO = 0";
        }
        jButtonIncluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(false);

        preencherTabelaMedico(sql);
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jTableMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMedicosMouseClicked

        // TODO add your handling code here:
        //String Nome = "" + jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 1);
        String idMedico = "" + jTableMedicos.getValueAt(jTableMedicos.getSelectedRow(), 0);
        conBd.conectarBd();
        try {

            String sql = "SELECT MEDICO.IDMEDICO, MEDICO.NOMEMEDICO, MEDICO.CPF, MEDICO.RG, MEDICO.TELRESIDENCIAL,MEDICO.TELCELULAR, MEDICO.LOGRADOURO,"
                    + "MEDICO.BAIRRO, MEDICO.NUMERO, MEDICO.CEP,MEDICO.COMPL, MEDICO.EMAIL, MEDICO.CRM, ESPECIALIDADE.IDESPECIALIDADE,ESPECIALIDADE.ESPEC,"
                    + "MEDICO.ESTADO, MEDICO.CIDADE, MEDICO.ATIVO FROM MEDICO INNER JOIN ESPECIALIDADE ON MEDICO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE "
                    + "WHERE MEDICO.IDMEDICO =" + idMedico;

            conBd.executaSql(sql);
            conBd.rs.first();

            LimparCampos();
            DesabilitarCampos();

            jTextFieldIDMedico.setText(String.valueOf(conBd.rs.getInt("IDMEDICO")));
            jTextFieldNomeMed.setText(conBd.rs.getString("NOMEMEDICO"));
            jTextFieldEndereco.setText(conBd.rs.getString("LOGRADOURO"));
            jTextFieldNumero.setText(String.valueOf(conBd.rs.getInt("NUMERO")));
            jTextFieldBairro.setText(conBd.rs.getString("BAIRRO"));
            jFormattedTextFieldCpf.setText(conBd.rs.getString("CPF"));
            jFormattedTextFieldRg.setText(conBd.rs.getString("RG"));
            jFormattedTextFieldTelRes.setText(conBd.rs.getString("TELRESIDENCIAL"));
            jFormattedTextFieldTelCel.setText(conBd.rs.getString("TELCELULAR"));
            jFormattedTextFieldCrm.setText(conBd.rs.getString("CRM"));
            jFormattedTextFieldCEP.setText(conBd.rs.getString("CEP"));
            jTextFieldCompl.setText(conBd.rs.getString("COMPL"));
            jComboBoxEspecializacao.setSelectedItem(conBd.rs.getString("ESPEC"));
            jTextFieldCidade.setText(conBd.rs.getString("CIDADE"));
            jTextFieldUF.setText(conBd.rs.getString("ESTADO"));
            jTextFieldEmail.setText(conBd.rs.getString("EMAIL"));
            jCheckBoxMedicoAtivo.setSelected(conBd.rs.getBoolean("ATIVO"));
            jTextFieldPesquisa.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar os dados" + ex.getMessage());
        }
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        conBd.DesconectarBd();
    }//GEN-LAST:event_jTableMedicosMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:

        //Limpar os campos
        LimparCampos();

        //Habilitar ou Desabilitar Campos
        DesabilitarCampos();
        jButtonBuscarCep.setEnabled(false);
        jTextFieldPesquisa.setEditable(true);
        jButtonCancelar.setEnabled(false);
        jButtonIncluir.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPesquisa.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        preencherTabelaMedico("SELECT IDMEDICO,NOMEMEDICO,ESPEC,CRM,MEDICO.ATIVO FROM MEDICO (NOLOCK) "
                + "INNER JOIN ESPECIALIDADE (NOLOCK) ON MEDICO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE ORDER BY NOMEMEDICO");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir? ");

        if (resposta == JOptionPane.YES_OPTION) {
            mod.setMcod(Integer.parseInt(jTextFieldIDMedico.getText()));
            controlM.Excluir(mod);
            preencherTabelaMedico("SELECT IDMEDICO,NOMEMEDICO,ESPEC,CRM,MEDICO.ATIVO FROM MEDICO (NOLOCK) "
                    + "INNER JOIN ESPECIALIDADE (NOLOCK) ON MEDICO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE ORDER BY NOMEMEDICO");

            jButtonSalvar.setEnabled(false);
            jButtonBuscarCep.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonIncluir.setEnabled(true);
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);

            LimparCampos();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (jTextFieldNomeMed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o NOME para continuar.");
            jTextFieldNomeMed.requestFocus();
        } else if (jFormattedTextFieldCrm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o CRM para continuar.");
            jFormattedTextFieldCrm.requestFocus();
        }

        if (flag == 1) {
            //Ler campos da tela de cadastro do medico

            mod.setMnome(jTextFieldNomeMed.getText());
            mod.setMcpf(jFormattedTextFieldCpf.getText());
            mod.setMrg(jFormattedTextFieldRg.getText());
            mod.setMtelcelular(jFormattedTextFieldTelCel.getText());
            mod.setMtelresidencial(jFormattedTextFieldTelRes.getText());
            mod.setMlogradouro(jTextFieldEndereco.getText());
            mod.setMbairro(jTextFieldBairro.getText());
            mod.setMnumero(Integer.parseInt(jTextFieldNumero.getText()));
            mod.setMcrm(jFormattedTextFieldCrm.getText());
            mod.setMcep(jFormattedTextFieldCEP.getText());
            mod.setMSCidade(jTextFieldCidade.getText());
            mod.setMSUf(jTextFieldUF.getText());
            mod.setMcompl(jTextFieldCompl.getText());
            mod.setMespecialidade(DaoEspecialidade.buscaEspecialidadePorNome((String) jComboBoxEspecializacao.getSelectedItem()));// teste index pega inteiros
            mod.setMEmail(jTextFieldEmail.getText());
            mod.setMAtivo(jCheckBoxMedicoAtivo.isSelected());
            controlM.salvar(mod);

            preencherTabelaMedico("SELECT IDMEDICO,NOMEMEDICO,ESPEC,CRM,MEDICO.ATIVO FROM MEDICO (NOLOCK) "
                    + "INNER JOIN ESPECIALIDADE (NOLOCK) ON MEDICO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE ORDER BY NOMEMEDICO");
            //Limpar os campos
            //LimparCampos();
            DesabilitarCampos();
            // flag = 0;
        } else if (flag == 2) {

            mod.setMnome(jTextFieldNomeMed.getText());
            mod.setMcpf(jFormattedTextFieldCpf.getText());
            mod.setMrg(jFormattedTextFieldRg.getText());
            mod.setMtelcelular(jFormattedTextFieldTelCel.getText());
            mod.setMtelresidencial(jFormattedTextFieldTelRes.getText());
            mod.setMlogradouro(jTextFieldEndereco.getText());
            mod.setMbairro(jTextFieldBairro.getText());
            mod.setMnumero(Integer.parseInt(jTextFieldNumero.getText()));
            mod.setMcrm(jFormattedTextFieldCrm.getText());
            mod.setMcep(jFormattedTextFieldCEP.getText());
            mod.setMSCidade(jTextFieldCidade.getText());
            mod.setMSUf(jTextFieldUF.getText());
            mod.setMcompl(jTextFieldCompl.getText());
            mod.setMespecialidade(DaoEspecialidade.buscaEspecialidadePorNome(
                    (String) jComboBoxEspecializacao.getSelectedItem()));
            mod.setMEmail(jTextFieldEmail.getText());
            mod.setMAtivo(jCheckBoxMedicoAtivo.isSelected());
            mod.setMcod(Integer.parseInt(jTextFieldIDMedico.getText()));
            controlM.Editar(mod);

            preencherTabelaMedico("SELECT IDMEDICO,NOMEMEDICO,ESPEC,CRM,MEDICO.ATIVO FROM MEDICO (NOLOCK) "
                    + "INNER JOIN ESPECIALIDADE (NOLOCK) ON MEDICO.IDESPECIALIDADE = ESPECIALIDADE.IDESPECIALIDADE ORDER BY NOMEMEDICO");

            //Desaabilitar Campos tela cadastro Medico
            DesabilitarCampos();
            //LimparCampos();
            //flag = 0;
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed

        flag = 1;
        //Limpar os campos
        LimparCampos();
        //metodo para preencher Jcombox Especialidade
        this.preencherEspecialidade();
        this.preencherIdMedicoIncluir();// preencherIdMedicoIncluir();
        HabilitarCampos();

        jButtonBuscarCep.setEnabled(true);
        jTextFieldPesquisa.setEditable(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:

        flag = 2;
        HabilitarCampos();
        jTextFieldPesquisa.setText("");
        jButtonSalvar.setEnabled(true);
        jButtonBuscarCep.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonIncluir.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jComboBoxEspecializacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspecializacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEspecializacaoActionPerformed

    private void jComboBoxEspecializacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEspecializacaoMouseClicked
        preencherEspecialidade();
    }//GEN-LAST:event_jComboBoxEspecializacaoMouseClicked

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jFormattedTextFieldTelResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelResActionPerformed

    private void jTextFieldNomeMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeMedActionPerformed

    private void jFormattedTextFieldCrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCrmActionPerformed

    private void jFormattedTextFieldRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldRgActionPerformed

    private void jRadioButtonFiltroMedicoTodosAtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroMedicoTodosAtivoMouseClicked
        // TODO add your handling code here:
//        if(jRadioButtonFiltroMedicoTodosAtivo.isSelected()){
//            jRadioButtonFiltroMedicoAtivo.setSelected(false);
//            jRadioButtonFiltroMedicoNaoAtivo.setSelected(false);
//        }

    }//GEN-LAST:event_jRadioButtonFiltroMedicoTodosAtivoMouseClicked

    private void jRadioButtonFiltroMedicoTodosAtivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroMedicoTodosAtivoStateChanged
        // TODO add your handling code here:

        if (jRadioButtonFiltroMedicoTodosAtivo.isSelected()) {
            jRadioButtonFiltroMedicoAtivo.setSelected(false);
            jRadioButtonFiltroMedicoNaoAtivo.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFiltroMedicoTodosAtivoStateChanged

    private void jRadioButtonFiltroMedicoAtivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroMedicoAtivoStateChanged
        if (jRadioButtonFiltroMedicoNaoAtivo.isSelected()) {
            jRadioButtonFiltroMedicoNaoAtivo.setSelected(false);
            jRadioButtonFiltroMedicoTodosAtivo.setSelected(false);
        }
        if (jRadioButtonFiltroMedicoTodosAtivo.isSelected()) {
            jRadioButtonFiltroMedicoTodosAtivo.setSelected(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFiltroMedicoAtivoStateChanged

    private void jRadioButtonFiltroMedicoNaoAtivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonFiltroMedicoNaoAtivoStateChanged
        // TODO add your handling code here:
        if (jRadioButtonFiltroMedicoAtivo.isSelected()) {
            jRadioButtonFiltroMedicoAtivo.setSelected(false);
        }
        if (jRadioButtonFiltroMedicoTodosAtivo.isSelected()) {
            jRadioButtonFiltroMedicoTodosAtivo.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFiltroMedicoNaoAtivoStateChanged
    public void preencherIdMedicoIncluir() {
        try {
            conBd.conectarBd();
            String sql = "SELECT MAX(IDMEDICO+1) AS PROXID FROM MEDICO (NOLOCK)";
            conBd.executaSql(sql);

            conBd.rs.first();

            jTextFieldIDMedico.setText(String.valueOf(conBd.rs.getInt("PROXID")));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar o proximo ID do médico! " + ex.getMessage());
        }
        conBd.DesconectarBd();
    }

    public void preencherEspecialidade() {
        conBd.conectarBd();

        try {

            jComboBoxEspecializacao.addItem("Selecione");
            String sql = "SELECT ESPEC FROM ESPECIALIDADE (NOLOCK) WHERE ATIVO = 1 ORDER BY ESPEC";

            pstM = conBd.con.prepareStatement(sql);
            rs = pstM.executeQuery();

            while (rs.next()) {
                jComboBoxEspecializacao.addItem(rs.getString("ESPEC"));
            }

        } catch (SQLException ex) {
            // Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher os dados da especialidade" + ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher os dados da especialidade" + ex.getMessage());
        }

        conBd.DesconectarBd();
    }

    public void HabilitarCampos() {
        jButtonSalvar.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldEndereco.setEnabled(true);
        jTextFieldNomeMed.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jComboBoxEspecializacao.setEnabled(true);
        jTextFieldUF.setEnabled(true);
        jFormattedTextFieldCpf.setEnabled(true);
        jFormattedTextFieldCrm.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldTelCel.setEnabled(true);
        jFormattedTextFieldTelRes.setEnabled(true);
        jFormattedTextFieldCEP.setEnabled(true);
        jTextFieldCompl.setEnabled(true);
        jButtonBuscarCep.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jCheckBoxMedicoAtivo.setEnabled(true);
    }

    public void DesabilitarCampos() {
        jButtonSalvar.setEnabled(false);
        jTextFieldBairro.setEnabled(false);
        jTextFieldEndereco.setEnabled(false);
        jTextFieldNomeMed.setEnabled(false);
        jTextFieldNumero.setEnabled(false);
        jComboBoxEspecializacao.setEnabled(false);
        jTextFieldUF.setEnabled(false);
        jFormattedTextFieldCpf.setEnabled(false);
        jFormattedTextFieldCrm.setEnabled(false);
        jFormattedTextFieldRg.setEnabled(false);
        jFormattedTextFieldTelCel.setEnabled(false);
        jFormattedTextFieldTelRes.setEnabled(false);
        jFormattedTextFieldCEP.setEnabled(false);
        jTextFieldCompl.setEnabled(false);
        jButtonBuscarCep.setEnabled(false);
        jTextFieldCidade.setEnabled(false);
        jTextFieldEmail.setEnabled(false);//editable
        jCheckBoxMedicoAtivo.setEnabled(false);
    }

    public void LimparCampos() {

        jTextFieldPesquisa.setText("");
        jTextFieldBairro.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldNomeMed.setText("");
        jTextFieldNumero.setText("");
        jComboBoxEspecializacao.setSelectedItem("Selecione");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldCrm.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldTelCel.setText("");
        jFormattedTextFieldTelRes.setText("");
        jFormattedTextFieldCEP.setText("");
        jTextFieldCompl.setText("");
        jTextFieldIDMedico.setText("");
        jTextFieldCidade.setText("");
        jTextFieldUF.setText("");
        jTextFieldEmail.setText("");
        jCheckBoxMedicoAtivo.setSelected(false);
    }

    @SuppressWarnings("unchecked")
    public final void preencherTabelaMedico(String sql) {

        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "NOME", "ESPECIALIDADE", "CRM", "ATIVO"};
        String ativo;
        conBd.conectarBd();

        conBd.executaSql(sql);

        try {
            conBd.rs.first();
            do {
                if (conBd.rs.getBoolean("ATIVO") == true) {
                    ativo = "Sim";
                } else {
                    ativo = "Não";
                }
                dados.add(new Object[]{conBd.rs.getInt("IDMEDICO"), conBd.rs.getString("NOMEMEDICO"),
                    conBd.rs.getString("ESPEC"), conBd.rs.getString("CRM"), ativo});

            } while (conBd.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher os dados da tabela." + ex.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTableMedicos.setModel(modelo);
        jTableMedicos.getBorder();

        jTableMedicos.getColumnModel().getColumn(0).setPreferredWidth(28);//Tamanho da tabela
        jTableMedicos.getColumnModel().getColumn(0).setResizable(false);

        jTableMedicos.getColumnModel().getColumn(1).setPreferredWidth(237);
        jTableMedicos.getColumnModel().getColumn(1).setResizable(false);

        jTableMedicos.getColumnModel().getColumn(2).setPreferredWidth(115);
        jTableMedicos.getColumnModel().getColumn(2).setResizable(false);

        jTableMedicos.getColumnModel().getColumn(3).setPreferredWidth(105);
        jTableMedicos.getColumnModel().getColumn(3).setResizable(false);

        jTableMedicos.getColumnModel().getColumn(4).setPreferredWidth(45);
        jTableMedicos.getColumnModel().getColumn(4).setResizable(false);

        jTableMedicos.getTableHeader().setReorderingAllowed(false);//reorganizar o cabeçalho
        jTableMedicos.setAutoResizeMode(jTableMedicos.AUTO_RESIZE_OFF); //NÃO VAI PODER REDIMENCIONAR A TABELA
        jTableMedicos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selecionar um por vez 
        //total do tamanho dos campos = 38 + 237 + 110 + 65 = 450
        conBd.DesconectarBd();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelMCep;
    private javax.swing.JButton jButtonBuscarCep;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckBoxMedicoAtivo;
    private javax.swing.JComboBox<String> jComboBoxEspecializacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldCrm;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelRes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadMedicos;
    private javax.swing.JLabel jLabelMBairro;
    private javax.swing.JLabel jLabelMComplemento;
    private javax.swing.JLabel jLabelMCpf;
    private javax.swing.JLabel jLabelMCrm;
    private javax.swing.JLabel jLabelMEndereco;
    private javax.swing.JLabel jLabelMEspecialidade;
    private javax.swing.JLabel jLabelMNome;
    private javax.swing.JLabel jLabelMNumero;
    private javax.swing.JLabel jLabelMRg;
    private javax.swing.JLabel jLabelMTelCel;
    private javax.swing.JLabel jLabelMTelRes;
    private javax.swing.JLabel jLabelMUf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFiltroMedicoAtivo;
    private javax.swing.JRadioButton jRadioButtonFiltroMedicoNaoAtivo;
    private javax.swing.JRadioButton jRadioButtonFiltroMedicoTodosAtivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMedicos;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCompl;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldIDMedico;
    private javax.swing.JTextField jTextFieldNomeMed;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldUF;
    // End of variables declaration//GEN-END:variables

}
